version: "3.8"

services:
  storage:
    image: quay.io/minio/minio:latest
    container_name: market_storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - market_store_vol:/data
    networks:
      - market_network
    command: server /data --console-address ":9001"

  database:
    image: postgres:latest
    container_name: market_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market
    ports:
      - "5432:5432"
    volumes:
      - market_db_vol:/var/lib/postgresql/data
    networks:
      - market_network

  # app:
  #   build: .
  #   container_name: tix_app
  #   restart: always
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #     storage:
  #       condition: service_started
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - tix_network

volumes:
  market_store_vol:
  market_db_vol:

networks:
  market_network:
